version: '3.0'
services:
  backend:
    container_name: opensky_backend
    build: 
        context: ../Backend
        dockerfile: ../Docker/opensky_backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Linux
    ports:
      - 9001:9001
  frontend:
    container_name: opensky_frontend
    build:
        context: ../Frontend/opensky-app
        dockerfile: ../../Docker/opensky_frontend/Dockerfile
    ports:
      - 4200:80